# Gunakan image resmi Node.js sebagai image dasar
FROM node:18-alpine

# Tetapkan direktori kerja di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Unduh dan instal dependensi proyek
RUN npm install

# Salin seluruh kode sumber aplikasi
COPY . .

# Paparkan port yang akan digunakan aplikasi (port frontend)
EXPOSE 5000

# Perintah default yang akan dijalankan saat container dimulai
# Pastikan ini menunjuk ke server.js
CMD ["node", "server.js"]